title = "Alvyl Consulting"
baseURL = ""
tags = ["portfolio", "consulting"]
languageCode = "en-us"
config = "config.toml"
theme = "osprey"
canonifyURLS = true

googleAnalytics = "UA-115982595-1"
disqusShortname = "alvylconsulting"

[Params]
    tagline = "We build, therefore we are."
    author = "Alvyl Creations"
    description = "Software Consulting services, Cloud Based SaaS platforms and DevOps."
    logoBig = "/images/alvylconsulting_logo_256px.svg"
    logoSmall = "/images/alvylconsulting_logo_256px.svg"
    favicon = "favicon.ico"
    opengraphImage = "/images/alvylconsulting_logo_256px.svg"
    twitter = "alvylconsulting"
    linkedin = "alvyl-consulting"
    github = "alvyl"
    email = "contact@alvyl.com"
    googleTagManager = "GTM-MTHP2LJ"
    googleSiteVerification = "iNLvksCkXJJdkF0boiXNEsKDIBbxNTJRadaruYyAnMU"
    highlightJS = true
    copyright = true
    credit = false
    customCSS = true
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = false

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Clients"
    url  = "/#work"
    weight = 2
[[menu.main]]
    name = "Team"
    url  = "/#team"
    weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4
